/*
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is generated from the generate-iconset command.
 * See icon-master-list.js for instructions
 */

import React from "react";
import { IconProvider } from "./icon";
import { IconShape } from "./icon-shape";

/**
 * The Icon Provider that contains all of the available Icons this application
 * utilizes.
 */
export const Icons: IconProvider = {
  [IconShape.NEW_ICON_NAME]: {
    baseWidth: 14,
    baseHeight: 14,
    render: (_color: string) => (
      <React.Fragment>
        <path
          d="M7 0.320312L13.6797 7L7 13.6797L5.82812 12.5078L10.4766 7.82031H0.320312V6.17969H10.4766L5.82812 1.49219L7 0.320312Z"
          fill="url(#paint0_linear_1503_6721)"
        />
        <defs>
          <linearGradient
            id="paint0_linear_1503_6721"
            x1="17"
            y1="7.05926"
            x2="-3"
            y2="7.05926"
            gradientUnits="userSpaceOnUse"
          >
            <stop stopColor="#E5506A" />
            <stop offset="1" stopColor="#8B42C4" />
          </linearGradient>
        </defs>
      </React.Fragment>
    ),
  },
  [IconShape.THUMBS_UP]: {
    baseWidth: 19,
    baseHeight: 19,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M2.61108 15.3058H5.29795V7.38911H2.61108V15.3058ZM17.3889 8.04883C17.3889 7.32313 16.7843 6.72938 16.0454 6.72938H11.8069L12.445 3.71445L12.4652 3.50334C12.4652 3.23286 12.351 2.98216 12.1696 2.80404L11.4576 2.11133L7.0377 6.4589C6.78917 6.6964 6.64139 7.02626 6.64139 7.38911V13.9863C6.64139 14.712 7.24593 15.3058 7.98482 15.3058H14.0303C14.5878 15.3058 15.0647 14.9759 15.2662 14.5009L17.2948 9.84987C17.3553 9.69813 17.3889 9.5398 17.3889 9.36827V8.04883Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.FOOTBALL]: {
    baseWidth: 20,
    baseHeight: 20,
    render: (color: string) => (
      <React.Fragment>
        <g fill={color} stroke="none">
          <path d="M1.0114 13.8252C0.926871 16.3823 1.34954 18.4111 1.71937 18.7809C2.0892 19.1508 4.12856 19.584 6.67512 19.4889L1.0114 13.8252Z" />
          <path d="M11.6414 0.786133C9.17941 1.22993 6.58002 2.20206 4.64632 4.14632C2.71263 6.09058 1.72993 8.67941 1.28613 11.1414L9.34848 19.2038C11.8211 18.7705 14.4099 17.7879 16.3436 15.8436C18.2773 13.8993 19.26 11.3105 19.7038 8.84848L11.6414 0.786133ZM8.28125 13.6986L6.80192 12.2192L12.7192 6.30192L14.1986 7.78125L8.28125 13.6986Z" />
          <path d="M19.9894 6.17507C20.0739 3.61794 19.6513 1.58915 19.2814 1.21932C18.9116 0.849486 16.8722 0.416253 14.3257 0.511353L19.9894 6.17507Z" />
        </g>
      </React.Fragment>
    ),
  },
  [IconShape.ACCOUNT_TREE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M22 11V3h-7v3H9V3H2v8h7V8h2v10h4v3h7v-8h-7v3h-2V8h2v3z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.ADD_CIRCLE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.ADD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.ARROW_DOWNWARD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m20 12-1.41-1.41L13 16.17V4h-2v12.17l-5.58-5.59L4 12l8 8 8-8z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.ARROW_RIGHT]: {
    baseWidth: 10,
    baseHeight: 10,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M5 0.324219L9.67578 5L5 9.67578L4.17969 8.85547L7.43359 5.57422H0.324219V4.42578H7.43359L4.17969 1.14453L5 0.324219Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.ARROW_LEFT]: {
    baseWidth: 22,
    baseHeight: 22,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M21.0195 9.76953V12.2305H5.78516L12.7578 19.2617L11 21.0195L0.980469 11L11 0.980469L12.7578 2.73828L5.78516 9.76953H21.0195Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.AUTO_AWESOME]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m19 9 1.25-2.75L23 5l-2.75-1.25L19 1l-1.25 2.75L15 5l2.75 1.25L19 9zm-7.5.5L9 4 6.5 9.5 1 12l5.5 2.5L9 20l2.5-5.5L17 12l-5.5-2.5zM19 15l-1.25 2.75L15 19l2.75 1.25L19 23l1.25-2.75L23 19l-2.75-1.25L19 15z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.BOLT]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M11 21h-1l1-7H7.5c-.58 0-.57-.32-.38-.66.19-.34.05-.08.07-.12C8.48 10.94 10.42 7.54 13 3h1l-1 7h3.5c.49 0 .56.33.47.51l-.07.15C12.96 17.55 11 21 11 21z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CALENDAR_TODAY]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 3h-1V1h-2v2H7V1H5v2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 18H4V10h16v11zm0-13H4V5h16v3z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CHECK]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M9 16.17 4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CIRCLE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CLOSE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CONTENT_COPY]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.CREDIT_CARD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 4H4c-1.11 0-1.99.89-1.99 2L2 18c0 1.11.89 2 2 2h16c1.11 0 2-.89 2-2V6c0-1.11-.89-2-2-2zm0 14H4v-6h16v6zm0-10H4V6h16v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.DASHBOARD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.DELETE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.DRAG_INDICATOR]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M11 18c0 1.1-.9 2-2 2s-2-.9-2-2 .9-2 2-2 2 .9 2 2zm-2-8c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0-6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm6 4c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.EDIT_NOTE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3 10h11v2H3v-2zm0-2h11V6H3v2zm0 8h7v-2H3v2zm15.01-3.13.71-.71a.996.996 0 0 1 1.41 0l.71.71c.39.39.39 1.02 0 1.41l-.71.71-2.12-2.12zm-.71.71-5.3 5.3V21h2.12l5.3-5.3-2.12-2.12z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.EDIT]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04a.996.996 0 0 0 0-1.41l-2.34-2.34a.996.996 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.EMAIL]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4-8 5-8-5V6l8 5 8-5v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.FLAG]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M14.4 6 14 4H5v17h2v-7h5.6l.4 2h7V6z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.FAVORITE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M16.5 5c-1.54 0-3.04.99-3.56 2.36h-1.87C10.54 5.99 9.04 5 7.5 5 5.5 5 4 6.5 4 8.5c0 2.89 3.14 5.74 7.9 10.05l.1.1.1-.1C16.86 14.24 20 11.39 20 8.5c0-2-1.5-3.5-3.5-3.5z"
          opacity=".3"
          fill={color}
        />
        <path
          d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.FILE_DOWNLOAD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.FILTER_LIST]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.FOLDER]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M10 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.FULLSCREEN]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.GAMEPAD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M15 7.5V2H9v5.5l3 3 3-3zM7.5 9H2v6h5.5l3-3-3-3zM9 16.5V22h6v-5.5l-3-3-3 3zM16.5 9l-3 3 3 3H22V9h-5.5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.HAMBURGER_MENU]: {
    baseWidth: 16,
    baseHeight: 10,
    render: (color: string) => (
      <React.Fragment>
        <path
          opacity="0.5"
          d="M0.5 0H15.5V1.67969H0.5V0ZM0.5 5.82031V4.17969H15.5V5.82031H0.5ZM0.5 10V8.32031H15.5V10H0.5Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.HELP]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.IMAGE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.INFO]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.INSIGHTS]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M21 8c-1.45 0-2.26 1.44-1.93 2.51l-3.55 3.56c-.3-.09-.74-.09-1.04 0l-2.55-2.55C12.27 10.45 11.46 9 10 9c-1.45 0-2.27 1.44-1.93 2.52l-4.56 4.55C2.44 15.74 1 16.55 1 18c0 1.1.9 2 2 2 1.45 0 2.26-1.44 1.93-2.51l4.55-4.56c.3.09.74.09 1.04 0l2.55 2.55C12.73 16.55 13.54 18 15 18c1.45 0 2.27-1.44 1.93-2.52l3.56-3.55c1.07.33 2.51-.48 2.51-1.93 0-1.1-.9-2-2-2z"
          fill={color}
        />
        <path
          d="m15 9 .94-2.07L18 6l-2.06-.93L15 3l-.92 2.07L12 6l2.08.93zM3.5 11 4 9l2-.5L4 8l-.5-2L3 8l-2 .5L3 9z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.KEYBOARD_ARROW_DOWN]: {
    baseWidth: 12,
    baseHeight: 8,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M1.98732 0.5L6.32909 4.84177L10.6709 0.5L12 1.82911L6.32909 7.5L0.658203 1.82911L1.98732 0.5Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.KEYBOARD_ARROW_LEFT]: {
    baseWidth: 19,
    baseHeight: 30,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M15 0L0 15L15 30L18.5156 26.4844L7.03125 15L18.5156 3.51562L15 0Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.KEYBOARD_ARROW_RIGHT]: {
    baseWidth: 19,
    baseHeight: 31,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M4 0.5L19 15.5L4 30.5L0.484375 26.9844L11.9688 15.5L0.484375 4.01562L4 0.5Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.KEYBOARD_ARROW_UP]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M7.41 15.41 12 10.83l4.59 4.58L18 14l-6-6-6 6z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.LABEL]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M17.63 5.84C17.27 5.33 16.67 5 16 5L5 5.01C3.9 5.01 3 5.9 3 7v10c0 1.1.9 1.99 2 1.99L16 19c.67 0 1.27-.33 1.63-.84L22 12l-4.37-6.16z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.LIST]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.LOCK]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.LIGHTBULB]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M9 21c0 .5.4 1 1 1h4c.6 0 1-.5 1-1v-1H9v1zm3-19C8.1 2 5 5.1 5 9c0 2.4 1.2 4.5 3 5.7V17c0 .5.4 1 1 1h6c.6 0 1-.5 1-1v-2.3c1.8-1.3 3-3.4 3-5.7 0-3.9-3.1-7-7-7z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.LOGOUT]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m17 7-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.MAIL]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4-8 5-8-5V6l8 5 8-5v2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PALETTE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 2C6.49 2 2 6.49 2 12s4.49 10 10 10a2.5 2.5 0 0 0 2.5-2.5c0-.61-.23-1.2-.64-1.67a.528.528 0 0 1-.13-.33c0-.28.22-.5.5-.5H16c3.31 0 6-2.69 6-6 0-4.96-4.49-9-10-9zm5.5 11c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5zm-3-4c-.83 0-1.5-.67-1.5-1.5S13.67 6 14.5 6s1.5.67 1.5 1.5S15.33 9 14.5 9zM5 11.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5S7.33 13 6.5 13 5 12.33 5 11.5zm6-4c0 .83-.67 1.5-1.5 1.5S8 8.33 8 7.5 8.67 6 9.5 6s1.5.67 1.5 1.5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PERCENT]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M7.5 11C9.43 11 11 9.43 11 7.5S9.43 4 7.5 4 4 5.57 4 7.5 5.57 11 7.5 11zm0-5C8.33 6 9 6.67 9 7.5S8.33 9 7.5 9 6 8.33 6 7.5 6.67 6 7.5 6zM4.002 18.583 18.59 3.996l1.414 1.414L5.417 19.997zM16.5 13c-1.93 0-3.5 1.57-3.5 3.5s1.57 3.5 3.5 3.5 3.5-1.57 3.5-3.5-1.57-3.5-3.5-3.5zm0 5c-.83 0-1.5-.67-1.5-1.5s.67-1.5 1.5-1.5 1.5.67 1.5 1.5-.67 1.5-1.5 1.5z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PERSON]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PHONE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PRIORITY_HIGH]: {
    baseWidth: 20,
    baseHeight: 20,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M8.82422 4.75H11.1758V11.75H8.82422V4.75ZM9.15234 14.9219C8.93359 14.6849 8.82422 14.4023 8.82422 14.0742C8.82422 13.7461 8.93359 13.4727 9.15234 13.2539C9.38932 13.0352 9.67188 12.9258 10 12.9258C10.3281 12.9258 10.6016 13.0352 10.8203 13.2539C11.0573 13.4727 11.1758 13.7461 11.1758 14.0742C11.1758 14.4023 11.0573 14.6849 10.8203 14.9219C10.6016 15.1406 10.3281 15.25 10 15.25C9.67188 15.25 9.38932 15.1406 9.15234 14.9219Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.PUBLISH]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M5 4v2h14V4H5zm0 10h4v6h6v-6h4l-7-7-7 7z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.REDEEM]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 6h-2.18c.11-.31.18-.65.18-1a2.996 2.996 0 0 0-5.5-1.65l-.5.67-.5-.68C10.96 2.54 10.05 2 9 2 7.34 2 6 3.34 6 5c0 .35.07.69.18 1H4c-1.11 0-1.99.89-1.99 2L2 19c0 1.11.89 2 2 2h16c1.11 0 2-.89 2-2V8c0-1.11-.89-2-2-2zm-5-2c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zM9 4c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zm11 15H4v-2h16v2zm0-5H4V8h5.08L7 10.83 8.62 12 11 8.76l1-1.36 1 1.36L15.38 12 17 10.83 14.92 8H20v6z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.REPLAY]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12 5V1L7 6l5 5V7c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69-6-6H4c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SEARCH]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SELL]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m21.41 11.41-8.83-8.83c-.37-.37-.88-.58-1.41-.58H4c-1.1 0-2 .9-2 2v7.17c0 .53.21 1.04.59 1.41l8.83 8.83c.78.78 2.05.78 2.83 0l7.17-7.17c.78-.78.78-2.04-.01-2.83zM6.5 8C5.67 8 5 7.33 5 6.5S5.67 5 6.5 5 8 5.67 8 6.5 7.33 8 6.5 8z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SETTINGS]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M19.14 12.94c.04-.3.06-.61.06-.94 0-.32-.02-.64-.07-.94l2.03-1.58a.49.49 0 0 0 .12-.61l-1.92-3.32a.488.488 0 0 0-.59-.22l-2.39.96c-.5-.38-1.03-.7-1.62-.94l-.36-2.54a.484.484 0 0 0-.48-.41h-3.84c-.24 0-.43.17-.47.41l-.36 2.54c-.59.24-1.13.57-1.62.94l-2.39-.96c-.22-.08-.47 0-.59.22L2.74 8.87c-.12.21-.08.47.12.61l2.03 1.58c-.05.3-.09.63-.09.94s.02.64.07.94l-2.03 1.58a.49.49 0 0 0-.12.61l1.92 3.32c.12.22.37.29.59.22l2.39-.96c.5.38 1.03.7 1.62.94l.36 2.54c.05.24.24.41.48.41h3.84c.24 0 .44-.17.47-.41l.36-2.54c.59-.24 1.13-.56 1.62-.94l2.39.96c.22.08.47 0 .59-.22l1.92-3.32c.12-.22.07-.47-.12-.61l-2.01-1.58zM12 15.6c-1.98 0-3.6-1.62-3.6-3.6s1.62-3.6 3.6-3.6 3.6 1.62 3.6 3.6-1.62 3.6-3.6 3.6z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SHARE]: {
    baseWidth: 16,
    baseHeight: 18,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M13 12.3984C13.6771 12.3984 14.25 12.6458 14.7188 13.1406C15.1875 13.6094 15.4219 14.1693 15.4219 14.8203C15.4219 15.4974 15.1745 16.0833 14.6797 16.5781C14.2109 17.0469 13.651 17.2812 13 17.2812C12.349 17.2812 11.776 17.0469 11.2812 16.5781C10.8125 16.0833 10.5781 15.4974 10.5781 14.8203C10.5781 14.5599 10.5911 14.3776 10.6172 14.2734L4.71875 10.8359C4.22396 11.2786 3.65104 11.5 3 11.5C2.32292 11.5 1.73698 11.2526 1.24219 10.7578C0.747396 10.263 0.5 9.67708 0.5 9C0.5 8.32292 0.747396 7.73698 1.24219 7.24219C1.73698 6.7474 2.32292 6.5 3 6.5C3.65104 6.5 4.22396 6.72135 4.71875 7.16406L10.5781 3.76562C10.526 3.50521 10.5 3.3099 10.5 3.17969C10.5 2.5026 10.7474 1.91667 11.2422 1.42188C11.737 0.927083 12.3229 0.679688 13 0.679688C13.6771 0.679688 14.263 0.927083 14.7578 1.42188C15.2526 1.91667 15.5 2.5026 15.5 3.17969C15.5 3.85677 15.2526 4.44271 14.7578 4.9375C14.263 5.43229 13.6771 5.67969 13 5.67969C12.375 5.67969 11.8021 5.44531 11.2812 4.97656L5.42188 8.41406C5.47396 8.67448 5.5 8.86979 5.5 9C5.5 9.13021 5.47396 9.32552 5.42188 9.58594L11.3594 13.0234C11.8281 12.6068 12.375 12.3984 13 12.3984Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SPACE_DASHBOARD]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M11 21H5c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2h6v18zm2 0h6c1.1 0 2-.9 2-2v-7h-8v9zm8-11V5c0-1.1-.9-2-2-2h-6v7h8z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SPEED]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m20.38 8.57-1.23 1.85a8 8 0 0 1-.22 7.58H5.07A8 8 0 0 1 15.58 6.85l1.85-1.23A10 10 0 0 0 3.35 19a2 2 0 0 0 1.72 1h13.85a2 2 0 0 0 1.74-1 10 10 0 0 0-.27-10.44zm-9.79 6.84a2 2 0 0 0 2.83 0l5.66-8.49-8.49 5.66a2 2 0 0 0 0 2.83z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SPORTS_ESPORTS]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m21.58 16.09-1.09-7.66A3.996 3.996 0 0 0 16.53 5H7.47C5.48 5 3.79 6.46 3.51 8.43l-1.09 7.66a2.545 2.545 0 0 0 4.32 2.16L9 16h6l2.25 2.25c.48.48 1.13.75 1.8.75 1.56 0 2.75-1.37 2.53-2.91zM11 11H9v2H8v-2H6v-1h2V8h1v2h2v1zm4-1c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm2 3c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.STAR]: {
    baseWidth: 20,
    baseHeight: 20,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M10 15.6779L16.18 19.3976L14.54 12.387L20 7.67014L12.81 7.06183L10 0.450195L7.19 7.06183L0 7.67014L5.46 12.387L3.82 19.3976L10 15.6779Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.SUBDIRECTORY_ARROW_RIGHT]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m19 15-6 6-1.42-1.42L15.17 16H4V4h2v10h9.17l-3.59-3.58L13 9l6 6z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TITLE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path d="M5 4v3h5.5v12h3V7H19V4z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.TERMINAL]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 4H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16c1.1 0 2-.9 2-2V6a2 2 0 0 0-2-2zm0 14H4V8h16v10zm-2-1h-6v-2h6v2zM7.5 17l-1.41-1.41L8.67 13l-2.59-2.59L7.5 9l4 4-4 4z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TRENDING_UP]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m16 6 2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TRENDING_DOWN]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="m16 18 2.29-2.29-4.88-4.88-4 4L2 7.41 3.41 6l6 6 4-4 6.3 6.29L22 12v6z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TRIANGLE_RIGHT]: {
    baseWidth: 20,
    baseHeight: 20,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M6.67969 4.17969L15.8203 10L6.67969 15.8203V4.17969Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TRIANGLE_DOWN]: {
    baseWidth: 10,
    baseHeight: 6,
    render: (color: string) => (
      <React.Fragment>
        <path d="M0 0.5H10L5 5.5L0 0.5Z" fill={color} />
      </React.Fragment>
    ),
  },
  [IconShape.UPLOAD_FILE]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm4 18H6V4h7v5h5v11zM8 15.01l1.41 1.41L11 14.84V19h2v-4.16l1.59 1.59L16 15.01 12.01 11z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.WEB]: {
    baseWidth: 24,
    baseHeight: 24,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-5 14H4v-4h11v4zm0-5H4V9h11v4zm5 5h-4V9h4v9z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
  [IconShape.TEXT_BLOCK]: {
    baseWidth: 8,
    baseHeight: 6,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3.3708 0.535156C2.98248 0.546181 2.60014 0.633675 2.24567 0.792633C1.8912 0.951591 1.57155 1.17889 1.30503 1.46152C1.03851 1.74416 0.830335 2.07658 0.692431 2.43976C0.554526 2.80293 0.489595 3.18974 0.501354 3.57805V3.95536C0.501354 4.25267 0.589514 4.54329 0.754687 4.79049C0.919859 5.03769 1.15462 5.23036 1.4293 5.34413C1.70397 5.4579 2.00621 5.48767 2.2978 5.42967C2.58939 5.37167 2.85723 5.2285 3.06746 5.01828C3.27768 4.80805 3.42084 4.54021 3.47885 4.24862C3.53685 3.95703 3.50708 3.65479 3.39331 3.38012C3.27953 3.10545 3.08687 2.87068 2.83967 2.70551C2.59247 2.54034 2.30184 2.45218 2.00454 2.45218C1.89062 2.45227 1.77716 2.46658 1.66678 2.49478C1.65238 2.49887 1.63706 2.49845 1.62291 2.49355C1.60876 2.48865 1.59645 2.47952 1.58767 2.46739C1.57954 2.45467 1.57522 2.43989 1.57522 2.42479C1.57522 2.40969 1.57954 2.39491 1.58767 2.38219C1.76262 2.0599 2.01974 1.78964 2.33291 1.59885C2.64608 1.40806 3.00417 1.30353 3.3708 1.29588C3.47168 1.29588 3.56842 1.2558 3.63976 1.18447C3.71109 1.11314 3.75116 1.0164 3.75116 0.915517C3.75116 0.814639 3.71109 0.717893 3.63976 0.646561C3.56842 0.57523 3.47168 0.535156 3.3708 0.535156Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M7.11982 1.29588C7.2207 1.29588 7.31745 1.2558 7.38878 1.18447C7.46011 1.11314 7.50018 1.0164 7.50018 0.915517C7.50018 0.814639 7.46011 0.717893 7.38878 0.646561C7.31745 0.57523 7.2207 0.535156 7.11982 0.535156C6.7315 0.546181 6.34916 0.633675 5.99469 0.792633C5.64022 0.951591 5.32058 1.17889 5.05405 1.46152C4.78753 1.74416 4.57936 2.07658 4.44145 2.43976C4.30355 2.80293 4.23862 3.18974 4.25038 3.57805V3.95536C4.24978 4.25353 4.33768 4.54516 4.50295 4.79332C4.66823 5.04149 4.90344 5.23502 5.17879 5.3494C5.45414 5.46378 5.75725 5.49386 6.04971 5.43584C6.34217 5.37782 6.61084 5.2343 6.82167 5.02347C7.0325 4.81264 7.17602 4.54397 7.23404 4.25151C7.29206 3.95905 7.26198 3.65594 7.1476 3.38059C7.03322 3.10524 6.83969 2.87003 6.59153 2.70475C6.34336 2.53948 6.05173 2.45157 5.75356 2.45218C5.63966 2.45246 5.52622 2.46677 5.4158 2.49478C5.4014 2.49887 5.38608 2.49845 5.37193 2.49355C5.35778 2.48865 5.34548 2.47952 5.33669 2.46739C5.32856 2.45467 5.32424 2.43989 5.32424 2.42479C5.32424 2.40969 5.32856 2.39491 5.33669 2.38219C5.51164 2.0599 5.76876 1.78964 6.08193 1.59885C6.39511 1.40806 6.75319 1.30353 7.11982 1.29588Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.TEXT_INPUT]: {
    baseWidth: 10,
    baseHeight: 6,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M10 1.33301C10 1.00149 9.8683 0.683545 9.63388 0.449124C9.39946 0.214704 9.08152 0.0830078 8.75 0.0830078H1.25C0.918479 0.0830078 0.600537 0.214704 0.366116 0.449124C0.131696 0.683545 0 1.00149 0 1.33301L0 4.66634C0 4.99786 0.131696 5.3158 0.366116 5.55023C0.600537 5.78465 0.918479 5.91634 1.25 5.91634H8.75C9.08152 5.91634 9.39946 5.78465 9.63388 5.55023C9.8683 5.3158 10 4.99786 10 4.66634V1.33301ZM9.16667 4.66634C9.16667 4.77685 9.12277 4.88283 9.04463 4.96097C8.96649 5.03911 8.86051 5.08301 8.75 5.08301H1.25C1.13949 5.08301 1.03351 5.03911 0.955372 4.96097C0.877232 4.88283 0.833333 4.77685 0.833333 4.66634V1.33301C0.833333 1.2225 0.877232 1.11652 0.955372 1.03838C1.03351 0.96024 1.13949 0.916341 1.25 0.916341H8.75C8.86051 0.916341 8.96649 0.96024 9.04463 1.03838C9.12277 1.11652 9.16667 1.2225 9.16667 1.33301V4.66634Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M3.33317 2.16634C3.44368 2.16634 3.54966 2.12244 3.6278 2.0443C3.70594 1.96616 3.74984 1.86018 3.74984 1.74967C3.74984 1.63917 3.70594 1.53319 3.6278 1.45505C3.54966 1.37691 3.44368 1.33301 3.33317 1.33301H2.08317C1.97266 1.33301 1.86668 1.37691 1.78854 1.45505C1.7104 1.53319 1.6665 1.63917 1.6665 1.74967C1.6665 1.86018 1.7104 1.96616 1.78854 2.0443C1.86668 2.12244 1.97266 2.16634 2.08317 2.16634H2.18734C2.21496 2.16634 2.24146 2.17732 2.26099 2.19685C2.28053 2.21639 2.2915 2.24288 2.2915 2.27051V3.72884C2.2915 3.75647 2.28053 3.78296 2.26099 3.8025C2.24146 3.82203 2.21496 3.83301 2.18734 3.83301H2.08317C1.97266 3.83301 1.86668 3.87691 1.78854 3.95505C1.7104 4.03319 1.6665 4.13917 1.6665 4.24967C1.6665 4.36018 1.7104 4.46616 1.78854 4.5443C1.86668 4.62244 1.97266 4.66634 2.08317 4.66634H3.33317C3.44368 4.66634 3.54966 4.62244 3.6278 4.5443C3.70594 4.46616 3.74984 4.36018 3.74984 4.24967C3.74984 4.13917 3.70594 4.03319 3.6278 3.95505C3.54966 3.87691 3.44368 3.83301 3.33317 3.83301H3.229C3.20138 3.83301 3.17488 3.82203 3.15535 3.8025C3.13581 3.78296 3.12484 3.75647 3.12484 3.72884V2.27051C3.12484 2.24288 3.13581 2.21639 3.15535 2.19685C3.17488 2.17732 3.20138 2.16634 3.229 2.16634H3.33317Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.TEXT_AREA]: {
    baseWidth: 12,
    baseHeight: 8,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M10.5834 0.333008H1.41667C1.17356 0.333008 0.940396 0.429585 0.768487 0.601495C0.596578 0.773404 0.5 1.00656 0.5 1.24968L0.5 6.74971C0.5 6.99283 0.596578 7.22599 0.768487 7.39789C0.940396 7.5698 1.17356 7.66638 1.41667 7.66638H10.5834C10.8265 7.66638 11.0597 7.5698 11.2316 7.39789C11.4035 7.22599 11.5001 6.99283 11.5001 6.74971V1.24968C11.5001 1.00656 11.4035 0.773404 11.2316 0.601495C11.0597 0.429585 10.8265 0.333008 10.5834 0.333008ZM1.41667 6.29137V1.70802C1.41667 1.58646 1.46496 1.46988 1.55092 1.38392C1.63687 1.29797 1.75345 1.24968 1.87501 1.24968H10.1251C10.2466 1.24968 10.3632 1.29797 10.4491 1.38392C10.5351 1.46988 10.5834 1.58646 10.5834 1.70802V6.29137C10.5834 6.41293 10.5351 6.52951 10.4491 6.61547C10.3632 6.70142 10.2466 6.74971 10.1251 6.74971H1.87501C1.75345 6.74971 1.63687 6.70142 1.55092 6.61547C1.46496 6.52951 1.41667 6.41293 1.41667 6.29137Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M2.3335 2.62467C2.3335 2.74623 2.38178 2.86281 2.46774 2.94876C2.55369 3.03472 2.67027 3.08301 2.79183 3.08301L9.20853 3.08301C9.33009 3.08301 9.44667 3.03472 9.53263 2.94876C9.61858 2.86281 9.66687 2.74623 9.66687 2.62467C9.66687 2.50311 9.61858 2.38653 9.53263 2.30058C9.44667 2.21462 9.33009 2.16634 9.20853 2.16634L2.79183 2.16634C2.67027 2.16634 2.55369 2.21462 2.46774 2.30058C2.38178 2.38653 2.3335 2.50311 2.3335 2.62467Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M2.3335 3.99967C2.3335 4.12123 2.38178 4.23781 2.46774 4.32376C2.55369 4.40972 2.67027 4.45801 2.79183 4.45801L9.20853 4.45801C9.33009 4.45801 9.44667 4.40972 9.53263 4.32376C9.61858 4.23781 9.66687 4.12123 9.66687 3.99967C9.66687 3.87811 9.61858 3.76153 9.53263 3.67558C9.44667 3.58962 9.33009 3.54134 9.20853 3.54134L2.79183 3.54134C2.67027 3.54134 2.55369 3.58962 2.46774 3.67558C2.38178 3.76153 2.3335 3.87811 2.3335 3.99967Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M2.3335 5.37467C2.3335 5.49623 2.38178 5.61281 2.46774 5.69876C2.55369 5.78472 2.67027 5.83301 2.79183 5.83301L6.00018 5.83301C6.12174 5.83301 6.23832 5.78472 6.32428 5.69876C6.41023 5.61281 6.45852 5.49623 6.45852 5.37467C6.45852 5.25311 6.41023 5.13653 6.32428 5.05058C6.23832 4.96462 6.12174 4.91634 6.00018 4.91634L2.79183 4.91634C2.67027 4.91634 2.55369 4.96462 2.46774 5.05058C2.38178 5.13653 2.3335 5.25311 2.3335 5.37467Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.CHECK_BOX]: {
    baseWidth: 8,
    baseHeight: 8,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M5.96559 2.31946C5.88772 2.26298 5.79068 2.23956 5.69562 2.25431C5.60056 2.26906 5.51518 2.32079 5.45809 2.39821L3.63809 4.87446L2.47142 3.94405C2.39407 3.88371 2.29591 3.85657 2.19855 3.86861C2.10119 3.88064 2.01259 3.93086 1.95226 4.00821C1.89192 4.08557 1.86478 4.18372 1.87682 4.28109C1.88885 4.37845 1.93907 4.46704 2.01642 4.52738L3.47476 5.69405C3.54348 5.73966 3.6262 5.7593 3.70809 5.74946C3.76465 5.74924 3.8204 5.73596 3.87098 5.71067C3.92157 5.68537 3.96564 5.64874 3.99976 5.60363L6.04142 2.8328C6.07045 2.79423 6.09153 2.75028 6.10344 2.7035C6.11535 2.65671 6.11785 2.60803 6.11079 2.56028C6.10374 2.51253 6.08727 2.46665 6.06234 2.42531C6.03742 2.38397 6.00453 2.34799 5.96559 2.31946Z"
          fill={color}
          stroke="none"
        />
        <path
          d="M6.91667 0.5H1.08333C0.928624 0.5 0.780251 0.561458 0.670854 0.670854C0.561458 0.780251 0.5 0.928624 0.5 1.08333L0.5 6.91667C0.5 7.07138 0.561458 7.21975 0.670854 7.32915C0.780251 7.43854 0.928624 7.5 1.08333 7.5H6.91667C7.07138 7.5 7.21975 7.43854 7.32915 7.32915C7.43854 7.21975 7.5 7.07138 7.5 6.91667V1.08333C7.5 0.928624 7.43854 0.780251 7.32915 0.670854C7.21975 0.561458 7.07138 0.5 6.91667 0.5V0.5ZM6.91667 6.84375C6.91667 6.86309 6.90898 6.88164 6.89531 6.89531C6.88164 6.90898 6.86309 6.91667 6.84375 6.91667H1.15625C1.13691 6.91667 1.11836 6.90898 1.10469 6.89531C1.09102 6.88164 1.08333 6.86309 1.08333 6.84375V1.15625C1.08333 1.13691 1.09102 1.11836 1.10469 1.10469C1.11836 1.09102 1.13691 1.08333 1.15625 1.08333H6.84375C6.86309 1.08333 6.88164 1.09102 6.89531 1.10469C6.90898 1.11836 6.91667 1.13691 6.91667 1.15625V6.84375Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.RADIO_BUTTON]: {
    baseWidth: 10,
    baseHeight: 10,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M2.40039 7.59961C3.13086 8.31576 3.9974 8.67383 5 8.67383C6.0026 8.67383 6.86198 8.31576 7.57812 7.59961C8.30859 6.86914 8.67383 6.0026 8.67383 5C8.67383 3.9974 8.30859 3.13802 7.57812 2.42188C6.86198 1.69141 6.0026 1.32617 5 1.32617C3.9974 1.32617 3.13086 1.69141 2.40039 2.42188C1.68424 3.13802 1.32617 3.9974 1.32617 5C1.32617 6.0026 1.68424 6.86914 2.40039 7.59961ZM1.75586 1.77734C2.6582 0.875 3.73958 0.423828 5 0.423828C6.26042 0.423828 7.33464 0.875 8.22266 1.77734C9.125 2.66536 9.57617 3.73958 9.57617 5C9.57617 6.26042 9.125 7.3418 8.22266 8.24414C7.33464 9.13216 6.26042 9.57617 5 9.57617C3.73958 9.57617 2.6582 9.13216 1.75586 8.24414C0.867839 7.3418 0.423828 6.26042 0.423828 5C0.423828 3.73958 0.867839 2.66536 1.75586 1.77734ZM3.36719 3.38867C3.82552 2.93034 4.36979 2.70117 5 2.70117C5.63021 2.70117 6.16732 2.93034 6.61133 3.38867C7.06966 3.83268 7.29883 4.36979 7.29883 5C7.29883 5.63021 7.06966 6.17448 6.61133 6.63281C6.16732 7.07682 5.63021 7.29883 5 7.29883C4.36979 7.29883 3.82552 7.07682 3.36719 6.63281C2.92318 6.17448 2.70117 5.63021 2.70117 5C2.70117 4.36979 2.92318 3.83268 3.36719 3.38867Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.SINGLE_SELECT]: {
    baseWidth: 12,
    baseHeight: 8,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M1 1.5C1 1.22386 1.22386 1 1.5 1H10.5C10.7761 1 11 1.22386 11 1.5V6.5C11 6.77614 10.7761 7 10.5 7H1.5C1.22386 7 1 6.77614 1 6.5V1.5Z"
          stroke={color}
          fill="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.LINE_ARROW_DOWN]: {
    baseWidth: 8,
    baseHeight: 5,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M3.64645 4.35355C3.84171 4.54882 4.15829 4.54882 4.35355 4.35355L7.53553 1.17157C7.7308 0.976311 7.7308 0.659728 7.53553 0.464466C7.34027 0.269204 7.02369 0.269204 6.82843 0.464466L4 3.29289L1.17157 0.464466C0.976311 0.269204 0.659728 0.269204 0.464466 0.464466C0.269204 0.659728 0.269204 0.976311 0.464466 1.17157L3.64645 4.35355ZM4.5 4L4.5 3L3.5 3L3.5 4L4.5 4Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.REPLAY_SMALL]: {
    baseWidth: 10,
    baseHeight: 13,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M5 2.92578C6.29427 2.92578 7.39714 3.38151 8.30859 4.29297C9.22005 5.20443 9.67578 6.29818 9.67578 7.57422C9.67578 8.86849 9.21094 9.97135 8.28125 10.8828C7.36979 11.7943 6.27604 12.25 5 12.25C3.72396 12.25 2.62109 11.7943 1.69141 10.8828C0.779948 9.97135 0.324219 8.86849 0.324219 7.57422H1.5C1.5 8.54036 1.83724 9.36979 2.51172 10.0625C3.20443 10.737 4.03385 11.0742 5 11.0742C5.96615 11.0742 6.78646 10.737 7.46094 10.0625C8.15365 9.36979 8.5 8.54036 8.5 7.57422C8.5 6.60807 8.15365 5.78776 7.46094 5.11328C6.78646 4.42057 5.96615 4.07422 5 4.07422V6.42578L2.07422 3.5L5 0.574219V2.92578Z"
          fill={color}
          stroke="none"
        />
      </React.Fragment>
    ),
  },
  [IconShape.BROWSER]: {
    baseWidth: 36,
    baseHeight: 36,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M35.0106 8.13574V31.8024C35.0106 32.587 34.6989 33.3395 34.1441 33.8943C33.5893 34.4491 32.8368 34.7607 32.0522 34.7607H3.94808C3.16348 34.7607 2.41102 34.4491 1.85622 33.8943C1.30143 33.3395 0.989746 32.587 0.989746 31.8024V8.13574H35.0106Z"
          fill="transparent"
        />
        <path
          d="M32.0522 0.73999H3.94808C2.31424 0.73999 0.989746 2.06448 0.989746 3.69832V31.8025C0.989746 33.4363 2.31424 34.7608 3.94808 34.7608H32.0522C33.6861 34.7608 35.0106 33.4363 35.0106 31.8025V3.69832C35.0106 2.06448 33.6861 0.73999 32.0522 0.73999Z"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M0.989746 8.13574H35.0106"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M6.16691 4.06812C6.24005 4.06812 6.31154 4.0898 6.37236 4.13044C6.43317 4.17107 6.48057 4.22882 6.50855 4.29639C6.53654 4.36396 6.54387 4.43832 6.5296 4.51005C6.51533 4.58178 6.48011 4.64767 6.42839 4.69939C6.37668 4.75111 6.31079 4.78632 6.23905 4.80059C6.16732 4.81486 6.09297 4.80754 6.0254 4.77955C5.95783 4.75156 5.90007 4.70416 5.85944 4.64335C5.81881 4.58254 5.79712 4.51104 5.79712 4.43791C5.79712 4.33983 5.83608 4.24577 5.90543 4.17642C5.97478 4.10708 6.06884 4.06812 6.16691 4.06812"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M10.6044 4.06812C10.6775 4.06812 10.749 4.0898 10.8099 4.13044C10.8707 4.17107 10.9181 4.22882 10.9461 4.29639C10.974 4.36396 10.9814 4.43832 10.9671 4.51005C10.9528 4.58178 10.9176 4.64767 10.8659 4.69939C10.8142 4.75111 10.7483 4.78632 10.6766 4.80059C10.6048 4.81486 10.5305 4.80754 10.4629 4.77955C10.3953 4.75156 10.3376 4.70416 10.2969 4.64335C10.2563 4.58254 10.2346 4.51104 10.2346 4.43791C10.2346 4.33983 10.2736 4.24577 10.3429 4.17642C10.4123 4.10708 10.5063 4.06812 10.6044 4.06812Z"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M15.0419 4.06812C15.115 4.06812 15.1865 4.0898 15.2474 4.13044C15.3082 4.17107 15.3556 4.22882 15.3836 4.29639C15.4115 4.36396 15.4189 4.43832 15.4046 4.51005C15.3903 4.58178 15.3551 4.64767 15.3034 4.69939C15.2517 4.75111 15.1858 4.78632 15.1141 4.80059C15.0423 4.81486 14.968 4.80754 14.9004 4.77955C14.8328 4.75156 14.7751 4.70416 14.7344 4.64335C14.6938 4.58254 14.6721 4.51104 14.6721 4.43791C14.6721 4.33983 14.7111 4.24577 14.7804 4.17642C14.8498 4.10708 14.9438 4.06812 15.0419 4.06812Z"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M29.8335 12.5732H6.16683C5.75837 12.5732 5.42725 12.9044 5.42725 13.3128V16.2712C5.42725 16.6796 5.75837 17.0107 6.16683 17.0107H29.8335C30.242 17.0107 30.5731 16.6796 30.5731 16.2712V13.3128C30.5731 12.9044 30.242 12.5732 29.8335 12.5732Z"
          fill="transparent"
        />
        <path
          d="M6.16683 12.5732C5.97068 12.5732 5.78256 12.6512 5.64387 12.7899C5.50517 12.9286 5.42725 13.1167 5.42725 13.3128V16.2712C5.42725 16.4673 5.50517 16.6554 5.64387 16.7941C5.78256 16.9328 5.97068 17.0107 6.16683 17.0107H23.1772L27.6147 12.5732H6.16683Z"
          fill="transparent"
        />
        <path
          d="M29.8335 12.5732H6.16683C5.75837 12.5732 5.42725 12.9044 5.42725 13.3128V16.2712C5.42725 16.6796 5.75837 17.0107 6.16683 17.0107H29.8335C30.242 17.0107 30.5731 16.6796 30.5731 16.2712V13.3128C30.5731 12.9044 30.242 12.5732 29.8335 12.5732Z"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M9.12516 19.9692H6.16683C5.75837 19.9692 5.42725 20.3004 5.42725 20.7088V29.5838C5.42725 29.9923 5.75837 30.3234 6.16683 30.3234H9.12516C9.53362 30.3234 9.86475 29.9923 9.86475 29.5838V20.7088C9.86475 20.3004 9.53362 19.9692 9.12516 19.9692Z"
          fill="transparent"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M14.3022 21.4482H29.0939"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M14.3022 24.4067H29.0939"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M14.3022 27.365H29.0939"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M14.3022 30.3232H24.6564"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </React.Fragment>
    ),
  },
  [IconShape.FILE_CODE]: {
    baseWidth: 30,
    baseHeight: 36,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M12.0416 13.3186L6.8645 18.4957L12.0416 23.6728"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M17.9583 13.3186L23.1353 18.4957L17.9583 23.6728"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M28.6185 6.65666C28.8959 6.93399 29.0518 7.31016 29.0519 7.70243V33.2817C29.0519 33.674 28.8961 34.0502 28.6187 34.3276C28.3413 34.605 27.9651 34.7608 27.5728 34.7608H2.42692C2.03462 34.7608 1.65839 34.605 1.38099 34.3276C1.10359 34.0502 0.947754 33.674 0.947754 33.2817V2.21916C0.947754 1.82686 1.10359 1.45063 1.38099 1.17323C1.65839 0.895831 2.03462 0.73999 2.42692 0.73999H22.0895C22.2844 0.741388 22.4772 0.781312 22.6567 0.857467C22.8361 0.933622 22.9988 1.04451 23.1353 1.18374L28.6185 6.65666Z"
          stroke={color}
          strokeWidth="1.47917"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </React.Fragment>
    ),
  },
  [IconShape.FTW360_UNIVERSITY_OF_UTAH]: {
    baseWidth: 45,
    baseHeight: 40,
    render: (color: string) => (
      <React.Fragment>
        <path
          d="M19.996 0H0V12.0451H3.98633V32.0773L11.959 40H32.0836L39.9919 32.0773V12.0451H44.0426V0H24.0466V12.0451H28.0329V28.0193H16.0739V11.9807H19.996V0Z"
          fill={color}
        />
      </React.Fragment>
    ),
  },
};
